version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: packing-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development